### ISSUE TITLE
Feature: JWT Authentication 

### ISSUE THREAD

**Issue by ProphetLamb** [Surreal-Net/Surreal.Net#2]
1. Specify how JWT authentication with surrealdb functions, and subsequently implement it for the Rest and RPC drivers.
2. Write tests for JWT authentication

**Comment by kgnet88** [comment]
Hi,

like I said in the mail, I am happy do give support. I will start here, because JWT is something I do almost daily at the moment. At least I want to try. The documentation is not there yet, but I think I can steal something from the other implementations...

**Comment by ProphetLamb** [comment]
Hey,
awesome! Thanks, that means a lot to me. I assigned the issue to you. Which you fun coding. Have a great day! ^^
