### ISSUE TITLE
Bug: Objects with a newline in the string cannot be created by DbRpc

### ISSUE THREAD

**Issue by Du-z** [Surreal-Net/Surreal.Net#20]
Cannot insert a object with a string that contains a new line character.

Uncomment the following line and run the test `RpcRoundTripTests.CreateRoundTripTest`

https://github.com/ProphetLamb/Surreal.Net/blob/3ed84b191f60a98dd82837beec744d3e71129ae6/tests/Core.Tests/RoundTripTests.cs#L120

**Comment by ProphetLamb** [comment]
This is related to an issue in the database engine https://github.com/surrealdb/surrealdb/issues/137 & https://github.com/surrealdb/surrealdb/issues/90.
SurrealDB does not accept any ascii and unicode escape sequences. The workaround is not to serialize escape sequences.
A sideaffect is that C-escape-sequences are not escaped aswell:
https://github.com/ProphetLamb/Surreal.Net/blob/71bc7d426f8087b04fccfee86b69dd07b1d1e2fe/src/Driver/Util.cs#L881-L882

**Comment by ProphetLamb** [comment]
Can be solved by wrapping the `JavaScriptEncoder.UnsafeRelaxedJsonEscaping` and handling c-escape-sequences manually

**Comment by tobiemh** [comment]
Hi @ProphetLamb , and @Du-z that's probably because of this bug https://github.com/surrealdb/surrealdb/issues/90 

Should be fixed soon...

**Comment by ProphetLamb** [comment]
Blocked until https://github.com/surrealdb/surrealdb/issues/90 is in release

**Comment by ProphetLamb** [comment]
This should work now! I am looking at other fixed testcases over at #72
