### ISSUE TITLE
Consider downgrading xUnit from 2.4.2 to 2.4.0

### ISSUE THREAD

**Issue by Du-z** [Surreal-Net/Surreal.Net#62]
I would like to improve the query tests by using member data. According to SO this should be straight forward. https://stackoverflow.com/a/55027598

However it looks like there is a regression in xUnit (https://github.com/xunit/xunit/issues/1983).

Otherwise we might need to think up another solution so we can use Member Data in these tests.

**Comment by ProphetLamb** [comment]
Sure thing, if you would open a PR thatd be awesome!

**Comment by ProphetLamb** [comment]
Closed with #63
