### ISSUE TITLE
Tests fail when run on SurealDB v1.0.0-beta.8

### ISSUE THREAD

**Issue by Du-z** [Surreal-Net/Surreal.Net#76]
Spent a few hours on this and couldn't get the basic Create then get by id to work.

Even via postman I cannot do `SELECT * FROM object WHERE id = "object:1405536926";`

**Comment by Du-z** [comment]
This is in Beta 8 and the test object was inserted using Rest Create endpoint 
![image](https://user-images.githubusercontent.com/16366766/193398227-a2661454-00b0-446b-9109-92090c4bcac3.png)

**Comment by Du-z** [comment]
It works when rolling back to Beta 7
![image](https://user-images.githubusercontent.com/16366766/193398248-6862c00f-70d7-4a94-a9eb-76155177decc.png)

**Comment by AntoniosBarotsis** [comment]
I haven't tried this myself but it probably makes more sense to post this to the [SurrealDB issues](https://github.com/surrealdb/surrealdb/issues/new/choose), not sure if this is intended or not.

**Comment by Du-z** [comment]
Yeah, wanted to confirm that it is now a issue from our implementation. But it is looking like it is a SurrealDB bug.

Bug raised here
https://github.com/surrealdb/surrealdb/issues/1281

**Comment by Du-z** [comment]
Workaround for bug is in #78 and should be removed when this bug is resolved.

**Comment by ProphetLamb** [comment]
Keeping this issue open, as blocked, until the issue is resolved

**Comment by ProphetLamb** [comment]
Solved with nightly branch
