### ISSUE TITLE
.NET Standard 20 Support

### ISSUE THREAD

**Issue by OfflinePing** [Surreal-Net/Surreal.Net#77]
**Is your feature request related to a problem? Please describe.**
I am using .NET Framework wich only works on Windows and Surreal.NET isn't working on it.

**Describe the solution you'd like**
I would love to see .NET Standard 20 Implementation / Support!

**Additional context**
Thank you for doing this in generell <3

**Comment by ProphetLamb** [comment]
Alright, I did some looking into it, and netstandard2.0 cannot be supported easily. A lot of API related to `Span`s changed, which the package makes extensive use of. .NET Framework 4.8 should be possible to support tho
